In [5]:
import polars as pl

In [7]:
df_train = pl.read_parquet("otto-recommender-system/train.parquet")
df_train

shape: (216716096, 4)
┌──────────┬─────────┬────────────┬──────┐
│ session  ┆ aid     ┆ ts         ┆ type │
│ ---      ┆ ---     ┆ ---        ┆ ---  │
│ i32      ┆ i32     ┆ i32        ┆ u8   │
╞══════════╪═════════╪════════════╪══════╡
│ 0        ┆ 1517085 ┆ 1659304800 ┆ 0    │
│ 0        ┆ 1563459 ┆ 1659304904 ┆ 0    │
│ 0        ┆ 1309446 ┆ 1659367439 ┆ 0    │
│ 0        ┆ 16246   ┆ 1659367719 ┆ 0    │
│ ...      ┆ ...     ┆ ...        ┆ ...  │
│ 12899777 ┆ 384045  ┆ 1661723976 ┆ 0    │
│ 12899777 ┆ 384045  ┆ 1661723986 ┆ 0    │
│ 12899778 ┆ 561560  ┆ 1661723983 ┆ 0    │
│ 12899778 ┆ 32070   ┆ 1661723994 ┆ 0    │
└──────────┴─────────┴────────────┴──────┘